#!/usr/bin/env bash
# Build notedrop.snplg: RN bundle + committed PluginConfig.json + icon, zipped.
# Output: build/outputs/notedrop.snplg (and build/generated/notedrop.bundle
# for hot reload). Never rewrites PluginConfig.json: the pluginID stays
# stable so a reinstall is an in-place upgrade.
set -euo pipefail
cd "$(dirname "$0")"

step() { printf '\n==> %s\n' "$*"; }

NAME=notedrop
GEN="$PWD/build/generated"
OUT="$PWD/build/outputs"
rm -rf "$GEN" "$OUT"
mkdir -p "$GEN" "$OUT"

[ -d node_modules ] || bun install
[ -f assets/icon.png ] || bun scripts/make-icon.ts

step "build stamp"
GIT="$(git rev-parse --short HEAD 2>/dev/null || echo nogit)"
if git status --porcelain -- . 2>/dev/null | grep -q .; then GIT="${GIT}-dirty"; fi
cat > src/buildStamp.ts <<EOF
// GENERATED by buildPlugin.sh, do not edit.
export const BUILD_STAMP = { git: '${GIT}', builtAt: '$(date -u +%Y-%m-%dT%H:%M:%SZ)' } as const;
EOF

step "bundling (metro, release)"
bunx react-native bundle \
  --entry-file index.js \
  --bundle-output "$GEN/$NAME.bundle" \
  --platform android \
  --assets-dest "$GEN" \
  --dev false \
  --reset-cache

step "staging config"
cp PluginConfig.json "$GEN/PluginConfig.json"
cp assets/icon.png "$GEN/icon.png"

step "packaging $NAME.snplg"
(cd "$GEN" && zip -qr "$OUT/$NAME.zip" .)
mv "$OUT/$NAME.zip" "$OUT/$NAME.snplg"
echo "OK: $OUT/$NAME.snplg"
